config/routes.rb
AngularTodo::Application.routes.draw do

  devise_for :users

  root 'lists#home'

  resources :users
  resources :lists, except: [:edit, :new]
  resources :tasks, except: [:edit, :new]

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list
  
  validates_presence_of :title
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  respond_to :json

  def home

  end

  def index
    @lists = user.lists.all
    
    respond_with(@lists) do |format|
      format.json {render json: @lists.as_json(:include => :tasks) }
    end
  end

  def show
    @list = user.lists.find(params[:id])

    respond_with(@list) do |format|
      format.json {render json: @list.as_json(:include => :tasks)}
    end
  end

  def create
    @list = user.lists.create!(list_params)

    respond_with(@list) do |format|
      format.json {render json: @list.as_json }
    end    
  end

  def destroy
    @list = user.lists.find(params[:id])

    @list.destroy

    respond_with(@list) do |format|
      format.json {render json: @list.as_json }
    end
  end

  def update
  end

  private

  def user
    User.find(current_user.id)
  end

  def list_params
    params.require(:list).permit(:title, :details, :id)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  respond_to :json

  
  def index
    @tasks = Task.all
    
    respond_with(@tasks) do |format|
      format.json {render json: @tasks.as_json }
    end
  end
  
  def show
    @task = Task.find(params[:id])

    respond_with(@task) do |format|
      format.json {render json: @task.as_json }
    end
  end

  def create
    @list = List.find(task_params[:list_id])

    @task = @list.tasks.create!(task_params)

    respond_with(@task) do |format|
      format.json {render json: @task.as_json }
    end    
  end

  def update
    @task = Task.find(task_params[:id])
    @task.update!(
      :checked => task_params[:checked]
    )
    
    respond_with(@task) do |format|
      format.json {render json: @task.as_json }
    end  
  end

  def destroy
  
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :goal_date, :checked, :list_id, :id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :json
  before_filter :authenticate_user!

  def show
    @user = current_user

    respond_with(@user) do |format|
      format.json {render json: @user.as_json }
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
        redirect_to :back
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @user = current_user
    respond_to do |format|
      if @user.update(user_params)
        format.json { head :no_content }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :provider, :uid)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user_content(&block)
    capture(&block) if current_user
  end

  def visitor_content(&block)
    capture(&block) unless current_user
  end

  def randomized_background_image
    images = ["assets/1-65b726fd202b510da78a95920cb700a3.png", "assets/2-b9fec92317ee123f1063c364874d439d.png", "assets/3-475e26ea5bbb6e4855ad4763ba375d0a.jpg", "assets/4-e757a45b9fc69b18057eb93705836486.jpg", "assets/5-aac87a420812511c5e17cea5e0447ba8.jpg", "assets/7-fda3e9b2cdd8ff0e6cb854088597eaf4.jpg", "assets/8-10eee685967f0a54b80dc61ec5fc4908.jpg", "assets/9-486f52e9a6a7e0a2db17969da8a5b0a5.jpg", "assets/10-fae21d9d8d45d816da68b0d5b3a1ef80.jpg"]
    images[rand(images.size)]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="Todo">
  <head>
    <title>AngularTodo</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    <!-- randomizes background -->
    <style type="text/css">
      body {
        background: url(<%= randomized_background_image %>) no-repeat top center fixed; 
      }
    </style>
  </head>
  <body ng-cloak class="container" id="body">
    <%= current_user_content do %>
      <h1 class="pull-left text-white"><a href="#">Git It Done</a></h1>
      <div class='row '>
        <div class='col-md-6 center-columns'>
          <ul class="nav nav-pills left-pad">
            <li><a ng-click="viewLists()" href="#"><span class="glyphicon glyphicon-align-justify"> My Lists</span></a></li>
            <li><a ng-click="createList()" href="#/list/new"><span class="glyphicon glyphicon-plus"> New List</span></a></li>
            <li><%= link_to("<span class='glyphicon glyphicon-cog'> Settings</span>".html_safe, edit_user_registration_path) %></li>
            <li><%= link_to("<span class='glyphicon glyphicon-off'> Logout</span>".html_safe, destroy_user_session_path, method: "delete") %></li>
          </ul>
        </div>
      </div>
    <% end %>
    <%= yield %>
    
    <%= yield :javascript %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/lists/home.html.erb
<%= current_user_content do %>
  <div ng-view></div>
<% end %>
<%= visitor_content do %>
  <div class="row">
    <div class="col-md-4 center-columns">
      <div class="row">
        <div class="col-md-12 text-center">
          <h1 class="homepage-header">Git It Done</h1>
        </div>
      </div>
      <div class="row">
      <div class="col-md-12">
          <div class="wrap">
            <p class="form-title">Sign In</p>
            <%= form_for("user", :url => user_session_path) do |f| %>
              <%= f.text_field :email, :autofocus => true, :class=>"", :placeholder => "Email" %>
              <%= f.password_field :password, :placeholder => "Password" %>
              <%= f.submit "SIGN IN", :class => "btn btn-success btn-sm" %>
              <div class="remember-forgot">
                <div class="row">
                  <div class="col-md-6">
                    <div class="checkbox">
                      <%= f.check_box :remember_me %> <%= f.label :remember_me %>
                    </div>
                  </div>
                  <div class="col-md-6 forgot-pass-content">
                    <%= link_to "forgot password?", new_password_path('user'), :class=>"text-muted small" %>
                  </div>
                </div>
              </div>
            <% end %>
              <div class="register">
                <h4 class="register-text">NEW MEMBER?</h4>
                <p class="register-text">Sign up to start creating your lists</p>
                <%= button_to "REGISTER", new_user_registration_path, :class => "btn btn-orange login-text", :method => :get%>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>